### PR TITLE
Create on-demand-workflow.yml

### PR DESCRIPTION
**Pull request by ramki11**
# Task

CICD pipeline using Github Actions. 
-Builds and Pushes the Frontend and Backend images to AWS ECR 
-Creates the task definition for Frontend and Backend images
-Deploys the Backend Image to AWS Fargate.

[Link to Ticket] https://incredihire-academy.atlassian.net/browse/SR-105

[Add links to additional documentation if exists. Otherwise, delete this block]

# Author Tasks
Currently running as on-demand workflow. Will change to Push on change after testing
## Acceptance Criteria
-Build and Deploy Frontend and Backend images to AWS Fargate on change.
- [ ] N/A

### CODE REVIEW

**Review by mcverter — DISMISSED** [review]
Looks good to me

**Review by jakethrasher — COMMENTED** [review]
This is a good start. Do you mind filling out the PR template? Thanks.

Also, there is a ticket for tracking this effort [here](https://incredihire-academy.atlassian.net/browse/SR-105)

**Review by ramki11 — COMMENTED** [review]
CICD pipeline using Github Actions.
-Builds and Pushes the Frontend and Backend images to AWS ECR
-Creates the task definition for Frontend and Backend images
-Deploys the Frontend and Backend Image to AWS Fargate.

**Comment by ramki11** [comment]
discard the PR

**Pull request closed without merging**
